### ISSUE TITLE
Add CI to test workflows

### ISSUE THREAD

**Issue by jennyfothergill** [mosdef-hub/mosdef_tutorials#31]
we could use [pytest plugin nbval](https://nbval.readthedocs.io/en/latest/) to check our notebooks. Here is an actions yml from our notebook tutorials repo:
```
name: Test PR and Image
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: cmelab/notebook-tutorials
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v1
    - name: test notebooks
      shell: bash -l {0}
      run: python -m pytest -v --nbval-lax
```
